[package]
name = "rcstat"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "cli",
    "core-functionality",
    "database",
    "utils"
]


[dependencies]
cli ={ path = "cli" }
core = { path = "core-functionality" }
database = { path = "database" }
utils = { path = "utils" }
